python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 10    --borf_batch_remove 10     --num_iterations 1
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 10    --borf_batch_remove 10     --num_iterations 2
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 10    --borf_batch_remove 10     --num_iterations 3
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 10    --borf_batch_remove 20     --num_iterations 1
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 10    --borf_batch_remove 20     --num_iterations 2
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 10    --borf_batch_remove 20     --num_iterations 3
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 10    --borf_batch_remove 30     --num_iterations 1
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 10    --borf_batch_remove 30     --num_iterations 2
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 10    --borf_batch_remove 30     --num_iterations 3
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 20    --borf_batch_remove 10     --num_iterations 1
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 20    --borf_batch_remove 10     --num_iterations 2
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 20    --borf_batch_remove 10     --num_iterations 3
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 20    --borf_batch_remove 20     --num_iterations 1
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 20    --borf_batch_remove 20     --num_iterations 2
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 20    --borf_batch_remove 20     --num_iterations 3
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 20    --borf_batch_remove 30     --num_iterations 1
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 20    --borf_batch_remove 30     --num_iterations 2
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 20    --borf_batch_remove 30     --num_iterations 3
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 30    --borf_batch_remove 10     --num_iterations 1
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 30    --borf_batch_remove 10     --num_iterations 2
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 30    --borf_batch_remove 10     --num_iterations 3
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 30    --borf_batch_remove 20     --num_iterations 1
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 30    --borf_batch_remove 20     --num_iterations 2
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 30    --borf_batch_remove 20     --num_iterations 3
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 30    --borf_batch_remove 30     --num_iterations 1
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 30    --borf_batch_remove 30     --num_iterations 2
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 30    --borf_batch_remove 30     --num_iterations 3
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 40    --borf_batch_remove 10     --num_iterations 1
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 40    --borf_batch_remove 10     --num_iterations 2
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 40    --borf_batch_remove 10     --num_iterations 3
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 40    --borf_batch_remove 20     --num_iterations 1
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 40    --borf_batch_remove 20     --num_iterations 2
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 40    --borf_batch_remove 20     --num_iterations 3
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 40    --borf_batch_remove 30     --num_iterations 1
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 40    --borf_batch_remove 30     --num_iterations 2
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 40    --borf_batch_remove 30     --num_iterations 3
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 50    --borf_batch_remove 10     --num_iterations 1
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 50    --borf_batch_remove 10     --num_iterations 2
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 50    --borf_batch_remove 10     --num_iterations 3
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 50    --borf_batch_remove 20     --num_iterations 1
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 50    --borf_batch_remove 20     --num_iterations 2
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 50    --borf_batch_remove 20     --num_iterations 3
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 50    --borf_batch_remove 30     --num_iterations 1
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 50    --borf_batch_remove 30     --num_iterations 2
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 50    --borf_batch_remove 30     --num_iterations 3
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 60    --borf_batch_remove 10     --num_iterations 1
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 60    --borf_batch_remove 10     --num_iterations 2
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 60    --borf_batch_remove 10     --num_iterations 3
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 60    --borf_batch_remove 20     --num_iterations 1
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 60    --borf_batch_remove 20     --num_iterations 2
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 60    --borf_batch_remove 20     --num_iterations 3
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 60    --borf_batch_remove 30     --num_iterations 1
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 60    --borf_batch_remove 30     --num_iterations 2
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 60    --borf_batch_remove 30     --num_iterations 3
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 70    --borf_batch_remove 10     --num_iterations 1
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 70    --borf_batch_remove 10     --num_iterations 2
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 70    --borf_batch_remove 10     --num_iterations 3
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 70    --borf_batch_remove 20     --num_iterations 1
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 70    --borf_batch_remove 20     --num_iterations 2
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 70    --borf_batch_remove 20     --num_iterations 3
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 70    --borf_batch_remove 30     --num_iterations 1
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 70    --borf_batch_remove 30     --num_iterations 2
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 70    --borf_batch_remove 30     --num_iterations 3
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 80    --borf_batch_remove 10     --num_iterations 1
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 80    --borf_batch_remove 10     --num_iterations 2
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 80    --borf_batch_remove 10     --num_iterations 3
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 80    --borf_batch_remove 20     --num_iterations 1
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 80    --borf_batch_remove 20     --num_iterations 2
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 80    --borf_batch_remove 20     --num_iterations 3
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 80    --borf_batch_remove 30     --num_iterations 1
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 80    --borf_batch_remove 30     --num_iterations 2
python run_node_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 80    --borf_batch_remove 30     --num_iterations 3
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 10    --borf_batch_remove 10     --num_iterations 1
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 10    --borf_batch_remove 10     --num_iterations 2
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 10    --borf_batch_remove 10     --num_iterations 3
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 10    --borf_batch_remove 20     --num_iterations 1
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 10    --borf_batch_remove 20     --num_iterations 2
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 10    --borf_batch_remove 20     --num_iterations 3
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 10    --borf_batch_remove 30     --num_iterations 1
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 10    --borf_batch_remove 30     --num_iterations 2
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 10    --borf_batch_remove 30     --num_iterations 3
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 20    --borf_batch_remove 10     --num_iterations 1
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 20    --borf_batch_remove 10     --num_iterations 2
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 20    --borf_batch_remove 10     --num_iterations 3
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 20    --borf_batch_remove 20     --num_iterations 1
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 20    --borf_batch_remove 20     --num_iterations 2
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 20    --borf_batch_remove 20     --num_iterations 3
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 20    --borf_batch_remove 30     --num_iterations 1
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 20    --borf_batch_remove 30     --num_iterations 2
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 20    --borf_batch_remove 30     --num_iterations 3
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 30    --borf_batch_remove 10     --num_iterations 1
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 30    --borf_batch_remove 10     --num_iterations 2
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 30    --borf_batch_remove 10     --num_iterations 3
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 30    --borf_batch_remove 20     --num_iterations 1
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 30    --borf_batch_remove 20     --num_iterations 2
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 30    --borf_batch_remove 20     --num_iterations 3
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 30    --borf_batch_remove 30     --num_iterations 1
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 30    --borf_batch_remove 30     --num_iterations 2
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 30    --borf_batch_remove 30     --num_iterations 3
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 40    --borf_batch_remove 10     --num_iterations 1
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 40    --borf_batch_remove 10     --num_iterations 2
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 40    --borf_batch_remove 10     --num_iterations 3
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 40    --borf_batch_remove 20     --num_iterations 1
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 40    --borf_batch_remove 20     --num_iterations 2
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 40    --borf_batch_remove 20     --num_iterations 3
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 40    --borf_batch_remove 30     --num_iterations 1
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 40    --borf_batch_remove 30     --num_iterations 2
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 40    --borf_batch_remove 30     --num_iterations 3
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 50    --borf_batch_remove 10     --num_iterations 1
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 50    --borf_batch_remove 10     --num_iterations 2
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 50    --borf_batch_remove 10     --num_iterations 3
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 50    --borf_batch_remove 20     --num_iterations 1
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 50    --borf_batch_remove 20     --num_iterations 2
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 50    --borf_batch_remove 20     --num_iterations 3
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 50    --borf_batch_remove 30     --num_iterations 1
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 50    --borf_batch_remove 30     --num_iterations 2
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 50    --borf_batch_remove 30     --num_iterations 3
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 60    --borf_batch_remove 10     --num_iterations 1
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 60    --borf_batch_remove 10     --num_iterations 2
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 60    --borf_batch_remove 10     --num_iterations 3
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 60    --borf_batch_remove 20     --num_iterations 1
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 60    --borf_batch_remove 20     --num_iterations 2
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 60    --borf_batch_remove 20     --num_iterations 3
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 60    --borf_batch_remove 30     --num_iterations 1
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 60    --borf_batch_remove 30     --num_iterations 2
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 60    --borf_batch_remove 30     --num_iterations 3
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 70    --borf_batch_remove 10     --num_iterations 1
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 70    --borf_batch_remove 10     --num_iterations 2
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 70    --borf_batch_remove 10     --num_iterations 3
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 70    --borf_batch_remove 20     --num_iterations 1
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 70    --borf_batch_remove 20     --num_iterations 2
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 70    --borf_batch_remove 20     --num_iterations 3
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 70    --borf_batch_remove 30     --num_iterations 1
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 70    --borf_batch_remove 30     --num_iterations 2
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 70    --borf_batch_remove 30     --num_iterations 3
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 80    --borf_batch_remove 10     --num_iterations 1
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 80    --borf_batch_remove 10     --num_iterations 2
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 80    --borf_batch_remove 10     --num_iterations 3
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 80    --borf_batch_remove 20     --num_iterations 1
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 80    --borf_batch_remove 20     --num_iterations 2
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 80    --borf_batch_remove 20     --num_iterations 3
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 80    --borf_batch_remove 30     --num_iterations 1
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 80    --borf_batch_remove 30     --num_iterations 2
python run_node_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 80    --borf_batch_remove 30     --num_iterations 3
