python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 1    --borf_batch_remove 0     --num_iterations 1
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 1    --borf_batch_remove 0     --num_iterations 2
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 1    --borf_batch_remove 0     --num_iterations 3
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 1    --borf_batch_remove 0     --num_iterations 4
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 1    --borf_batch_remove 0     --num_iterations 5
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 1    --borf_batch_remove 1     --num_iterations 1
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 1    --borf_batch_remove 1     --num_iterations 2
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 1    --borf_batch_remove 1     --num_iterations 3
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 1    --borf_batch_remove 1     --num_iterations 4
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 1    --borf_batch_remove 1     --num_iterations 5
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 1    --borf_batch_remove 2     --num_iterations 1
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 1    --borf_batch_remove 2     --num_iterations 2
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 1    --borf_batch_remove 2     --num_iterations 3
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 1    --borf_batch_remove 2     --num_iterations 4
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 1    --borf_batch_remove 2     --num_iterations 5
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 1    --borf_batch_remove 3     --num_iterations 1
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 1    --borf_batch_remove 3     --num_iterations 2
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 1    --borf_batch_remove 3     --num_iterations 3
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 1    --borf_batch_remove 3     --num_iterations 4
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 1    --borf_batch_remove 3     --num_iterations 5
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 2    --borf_batch_remove 0     --num_iterations 1
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 2    --borf_batch_remove 0     --num_iterations 2
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 2    --borf_batch_remove 0     --num_iterations 3
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 2    --borf_batch_remove 0     --num_iterations 4
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 2    --borf_batch_remove 0     --num_iterations 5
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 2    --borf_batch_remove 1     --num_iterations 1
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 2    --borf_batch_remove 1     --num_iterations 2
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 2    --borf_batch_remove 1     --num_iterations 3
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 2    --borf_batch_remove 1     --num_iterations 4
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 2    --borf_batch_remove 1     --num_iterations 5
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 2    --borf_batch_remove 2     --num_iterations 1
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 2    --borf_batch_remove 2     --num_iterations 2
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 2    --borf_batch_remove 2     --num_iterations 3
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 2    --borf_batch_remove 2     --num_iterations 4
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 2    --borf_batch_remove 2     --num_iterations 5
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 2    --borf_batch_remove 3     --num_iterations 1
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 2    --borf_batch_remove 3     --num_iterations 2
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 2    --borf_batch_remove 3     --num_iterations 3
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 2    --borf_batch_remove 3     --num_iterations 4
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 2    --borf_batch_remove 3     --num_iterations 5
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 3    --borf_batch_remove 0     --num_iterations 1
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 3    --borf_batch_remove 0     --num_iterations 2
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 3    --borf_batch_remove 0     --num_iterations 3
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 3    --borf_batch_remove 0     --num_iterations 4
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 3    --borf_batch_remove 0     --num_iterations 5
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 3    --borf_batch_remove 1     --num_iterations 1
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 3    --borf_batch_remove 1     --num_iterations 2
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 3    --borf_batch_remove 1     --num_iterations 3
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 3    --borf_batch_remove 1     --num_iterations 4
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 3    --borf_batch_remove 1     --num_iterations 5
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 3    --borf_batch_remove 2     --num_iterations 1
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 3    --borf_batch_remove 2     --num_iterations 2
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 3    --borf_batch_remove 2     --num_iterations 3
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 3    --borf_batch_remove 2     --num_iterations 4
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 3    --borf_batch_remove 2     --num_iterations 5
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 3    --borf_batch_remove 3     --num_iterations 1
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 3    --borf_batch_remove 3     --num_iterations 2
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 3    --borf_batch_remove 3     --num_iterations 3
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 3    --borf_batch_remove 3     --num_iterations 4
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 3    --borf_batch_remove 3     --num_iterations 5
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 4    --borf_batch_remove 0     --num_iterations 1
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 4    --borf_batch_remove 0     --num_iterations 2
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 4    --borf_batch_remove 0     --num_iterations 3
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 4    --borf_batch_remove 0     --num_iterations 4
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 4    --borf_batch_remove 0     --num_iterations 5
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 4    --borf_batch_remove 1     --num_iterations 1
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 4    --borf_batch_remove 1     --num_iterations 2
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 4    --borf_batch_remove 1     --num_iterations 3
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 4    --borf_batch_remove 1     --num_iterations 4
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 4    --borf_batch_remove 1     --num_iterations 5
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 4    --borf_batch_remove 2     --num_iterations 1
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 4    --borf_batch_remove 2     --num_iterations 2
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 4    --borf_batch_remove 2     --num_iterations 3
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 4    --borf_batch_remove 2     --num_iterations 4
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 4    --borf_batch_remove 2     --num_iterations 5
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 4    --borf_batch_remove 3     --num_iterations 1
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 4    --borf_batch_remove 3     --num_iterations 2
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 4    --borf_batch_remove 3     --num_iterations 3
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 4    --borf_batch_remove 3     --num_iterations 4
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 4    --borf_batch_remove 3     --num_iterations 5
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 5    --borf_batch_remove 0     --num_iterations 1
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 5    --borf_batch_remove 0     --num_iterations 2
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 5    --borf_batch_remove 0     --num_iterations 3
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 5    --borf_batch_remove 0     --num_iterations 4
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 5    --borf_batch_remove 0     --num_iterations 5
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 5    --borf_batch_remove 1     --num_iterations 1
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 5    --borf_batch_remove 1     --num_iterations 2
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 5    --borf_batch_remove 1     --num_iterations 3
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 5    --borf_batch_remove 1     --num_iterations 4
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 5    --borf_batch_remove 1     --num_iterations 5
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 5    --borf_batch_remove 2     --num_iterations 1
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 5    --borf_batch_remove 2     --num_iterations 2
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 5    --borf_batch_remove 2     --num_iterations 3
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 5    --borf_batch_remove 2     --num_iterations 4
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 5    --borf_batch_remove 2     --num_iterations 5
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 5    --borf_batch_remove 3     --num_iterations 1
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 5    --borf_batch_remove 3     --num_iterations 2
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 5    --borf_batch_remove 3     --num_iterations 3
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 5    --borf_batch_remove 3     --num_iterations 4
python run_graph_classification.py     --rewiring borf     --layer_type GCN    --num_trials 100    --device cuda:0    --borf_batch_add 5    --borf_batch_remove 3     --num_iterations 5
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 1    --borf_batch_remove 0     --num_iterations 1
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 1    --borf_batch_remove 0     --num_iterations 2
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 1    --borf_batch_remove 0     --num_iterations 3
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 1    --borf_batch_remove 0     --num_iterations 4
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 1    --borf_batch_remove 0     --num_iterations 5
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 1    --borf_batch_remove 1     --num_iterations 1
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 1    --borf_batch_remove 1     --num_iterations 2
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 1    --borf_batch_remove 1     --num_iterations 3
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 1    --borf_batch_remove 1     --num_iterations 4
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 1    --borf_batch_remove 1     --num_iterations 5
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 1    --borf_batch_remove 2     --num_iterations 1
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 1    --borf_batch_remove 2     --num_iterations 2
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 1    --borf_batch_remove 2     --num_iterations 3
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 1    --borf_batch_remove 2     --num_iterations 4
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 1    --borf_batch_remove 2     --num_iterations 5
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 1    --borf_batch_remove 3     --num_iterations 1
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 1    --borf_batch_remove 3     --num_iterations 2
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 1    --borf_batch_remove 3     --num_iterations 3
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 1    --borf_batch_remove 3     --num_iterations 4
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 1    --borf_batch_remove 3     --num_iterations 5
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 2    --borf_batch_remove 0     --num_iterations 1
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 2    --borf_batch_remove 0     --num_iterations 2
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 2    --borf_batch_remove 0     --num_iterations 3
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 2    --borf_batch_remove 0     --num_iterations 4
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 2    --borf_batch_remove 0     --num_iterations 5
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 2    --borf_batch_remove 1     --num_iterations 1
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 2    --borf_batch_remove 1     --num_iterations 2
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 2    --borf_batch_remove 1     --num_iterations 3
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 2    --borf_batch_remove 1     --num_iterations 4
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 2    --borf_batch_remove 1     --num_iterations 5
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 2    --borf_batch_remove 2     --num_iterations 1
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 2    --borf_batch_remove 2     --num_iterations 2
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 2    --borf_batch_remove 2     --num_iterations 3
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 2    --borf_batch_remove 2     --num_iterations 4
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 2    --borf_batch_remove 2     --num_iterations 5
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 2    --borf_batch_remove 3     --num_iterations 1
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 2    --borf_batch_remove 3     --num_iterations 2
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 2    --borf_batch_remove 3     --num_iterations 3
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 2    --borf_batch_remove 3     --num_iterations 4
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 2    --borf_batch_remove 3     --num_iterations 5
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 3    --borf_batch_remove 0     --num_iterations 1
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 3    --borf_batch_remove 0     --num_iterations 2
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 3    --borf_batch_remove 0     --num_iterations 3
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 3    --borf_batch_remove 0     --num_iterations 4
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 3    --borf_batch_remove 0     --num_iterations 5
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 3    --borf_batch_remove 1     --num_iterations 1
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 3    --borf_batch_remove 1     --num_iterations 2
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 3    --borf_batch_remove 1     --num_iterations 3
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 3    --borf_batch_remove 1     --num_iterations 4
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 3    --borf_batch_remove 1     --num_iterations 5
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 3    --borf_batch_remove 2     --num_iterations 1
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 3    --borf_batch_remove 2     --num_iterations 2
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 3    --borf_batch_remove 2     --num_iterations 3
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 3    --borf_batch_remove 2     --num_iterations 4
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 3    --borf_batch_remove 2     --num_iterations 5
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 3    --borf_batch_remove 3     --num_iterations 1
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 3    --borf_batch_remove 3     --num_iterations 2
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 3    --borf_batch_remove 3     --num_iterations 3
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 3    --borf_batch_remove 3     --num_iterations 4
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 3    --borf_batch_remove 3     --num_iterations 5
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 4    --borf_batch_remove 0     --num_iterations 1
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 4    --borf_batch_remove 0     --num_iterations 2
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 4    --borf_batch_remove 0     --num_iterations 3
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 4    --borf_batch_remove 0     --num_iterations 4
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 4    --borf_batch_remove 0     --num_iterations 5
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 4    --borf_batch_remove 1     --num_iterations 1
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 4    --borf_batch_remove 1     --num_iterations 2
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 4    --borf_batch_remove 1     --num_iterations 3
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 4    --borf_batch_remove 1     --num_iterations 4
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 4    --borf_batch_remove 1     --num_iterations 5
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 4    --borf_batch_remove 2     --num_iterations 1
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 4    --borf_batch_remove 2     --num_iterations 2
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 4    --borf_batch_remove 2     --num_iterations 3
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 4    --borf_batch_remove 2     --num_iterations 4
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 4    --borf_batch_remove 2     --num_iterations 5
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 4    --borf_batch_remove 3     --num_iterations 1
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 4    --borf_batch_remove 3     --num_iterations 2
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 4    --borf_batch_remove 3     --num_iterations 3
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 4    --borf_batch_remove 3     --num_iterations 4
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 4    --borf_batch_remove 3     --num_iterations 5
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 5    --borf_batch_remove 0     --num_iterations 1
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 5    --borf_batch_remove 0     --num_iterations 2
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 5    --borf_batch_remove 0     --num_iterations 3
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 5    --borf_batch_remove 0     --num_iterations 4
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 5    --borf_batch_remove 0     --num_iterations 5
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 5    --borf_batch_remove 1     --num_iterations 1
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 5    --borf_batch_remove 1     --num_iterations 2
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 5    --borf_batch_remove 1     --num_iterations 3
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 5    --borf_batch_remove 1     --num_iterations 4
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 5    --borf_batch_remove 1     --num_iterations 5
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 5    --borf_batch_remove 2     --num_iterations 1
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 5    --borf_batch_remove 2     --num_iterations 2
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 5    --borf_batch_remove 2     --num_iterations 3
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 5    --borf_batch_remove 2     --num_iterations 4
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 5    --borf_batch_remove 2     --num_iterations 5
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 5    --borf_batch_remove 3     --num_iterations 1
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 5    --borf_batch_remove 3     --num_iterations 2
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 5    --borf_batch_remove 3     --num_iterations 3
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 5    --borf_batch_remove 3     --num_iterations 4
python run_graph_classification.py     --rewiring borf     --layer_type GIN    --num_trials 100    --device cuda:0    --borf_batch_add 5    --borf_batch_remove 3     --num_iterations 5
